aws_paginate: optional get
lyft/cartography pull request #1020
Opened 2022-11-04 03:48 UTC by ramonpetgrave64

Optionally get the response object from aws_paginate()'s pages. This is useful for those opt-in regions where an API may simply not include the response object if a region is not enabled.
```
 {'ResponseMetadata': {'HTTPHeaders': {'connection': 'keep-alive',
                                      'content-length': '2',
                                      'content-type': 'application/json',
                                      'date': 'Fri, 01 Nov 2022 01:01:01 GMT',
                                      'x-amz-apigw-id': '<redacted>',
                                      'x-amzn-requestid': '<redacted>',
                                      'x-amzn-trace-id': 'Root=<redacted>'},
                      'HTTPStatusCode': 200,
                      'RequestId': '<redacted>',
                      'RetryAttempts': 0}} 
```

As apposed to 

```
 {'ResponseMetadata': {'HTTPHeaders': {'connection': 'keep-alive',
                                      'content-length': '2',
                                      'content-type': 'application/json',
                                      'date': 'Fri, 01 Nov 2022 01:01:01 GMT',
                                      'x-amz-apigw-id': '<redacted>',
                                      'x-amzn-requestid': '<redacted>',
                                      'x-amzn-trace-id': 'Root=<redacted>'},
                      'HTTPStatusCode': 200,
                      'RequestId': '<redacted>',
                      'RetryAttempts': 0},
  'findings':[...]
}
```

2022-11-07 05:18 UTC, ramonpetgrave64 commented
@achantavy

2022-11-07 19:03 UTC, achantavy requested changes

2022-11-08 17:37 UTC, achantavy approved these changes

2022-11-08 17:37 UTC, merged

2022-11-15 03:29 UTC, ramonpetgrave64 commented
related #988