Possible fix for #1032
lyft/cartography pull request #1033
Opened 2022-11-15 17:56 UTC by achantavy

Don't merge this yet until we know why this wasn't caught by our current CI int tests.

2023-02-14 23:07 UTC, kedarghule requested changes
I also noticed EXISTS needs to be changed in the below files (hopefully I have a updated version):
1) https://github.com/lyft/cartography/blob/c38aea6c6d6db6d725a63bd031b7af8727eb2afd/cartography/intel/aws/kms.py#L192

2) https://github.com/lyft/cartography/blob/c38aea6c6d6db6d725a63bd031b7af8727eb2afd/cartography/data/jobs/analysis/gcp_gke_basic_auth.json#L5

3) https://github.com/lyft/cartography/blob/c38aea6c6d6db6d725a63bd031b7af8727eb2afd/cartography/data/jobs/analysis/gcp_gke_basic_auth.json#L10

4) https://github.com/lyft/cartography/blob/c38aea6c6d6db6d725a63bd031b7af8727eb2afd/cartography/data/jobs/analysis/aws_ec2_keypair_analysis.json#L6

5) https://github.com/lyft/cartography/blob/c38aea6c6d6db6d725a63bd031b7af8727eb2afd/cartography/data/jobs/analysis/aws_ec2_keypair_analysis.json#L11

2023-02-14 23:10 UTC, achantavy commented on cartography/data/jobs/analysis/gcp_gke_basic_auth.json
>        "__comment": "This sets the basic_auth attribute",
Crap, good catch, thank you will fix

2023-03-13 02:07 UTC, achantavy commented
@kedarghule - ok! I think I got 'em all. Ran integration tests against a 5.x container and updated the install docs.

2023-03-13 15:25 UTC, kedarghule reviewed
@achantavy Looks good! I see one of the integration tests is failing. Should I still go ahead and approve and merge?

2023-03-14 06:48 UTC, achantavy commented
@kedarghule I finally was able to add a CI test suite for Neo4j 5! For some reason a manual install of that version kept failing on GitHub actions so I just gave up and used docker.

2023-03-14 19:01 UTC, kedarghule submitted a review, later dismissed
Sweet :D

2023-03-14 20:15 UTC, ramonpetgrave64 approved these changes

2023-03-14 20:19 UTC, achantavy commented
Let's do a follow up PR for a separate docker compose update

2023-03-14 20:19 UTC, merged