Ecs update task definitions import to greatly improve sync speed
lyft/cartography pull request #1127
Opened 2023-02-22 18:56 UTC by tmsteere

See https://github.com/lyft/cartography/issues/1126

This PR accomplishes the following: 
Updates the process to only import the actively used task definitions by parsing the tasks list for the taskDefinitionArn instead of ingesting all task definitions
Creating a relationship between the task definition and the task that definition is used by
Updates the tests for importing task definitions

2023-02-22 19:17 UTC, tmsteere commented
Integration tests currently fail with an attribute error if all tests are run. If only test_load_ecs_task_definitions or test_load_ecs_tasks are run independently they pass, but if run sequentially, they fail. Troubleshooting.

2023-02-23 06:48 UTC, achantavy commented
@ryan-lane - I think you have context on ECS, can you take a look if you have a chance?

2023-02-23 06:54 UTC, achantavy reviewed
@tmsteere - I think the int tests were failing because we have the pytest fixture set to 'module' scope and not 'function': https://github.com/lyft/cartography/blob/f613c32959f4bbdab53f83b2a03532c62e180e8d/tests/integration/conftest.py#L7, so the test_load_ecs_tasks() test may have been expecting the graph or some other data to already be a certain state before it ran.

Couple of options: 
1. Reorder the tests (which you have done already). Like you said, the downside is that one of the tests fails in isolation.
2. Get the failing test to have the state that it is expecting so that it passes both in isolation and in series. This could be hackily done by doing a `match(n) detach delete n;` before or after a test as part of an `# arrange` step.

I don't particularly have a strong opinion about either. The decision was made early on to have module scoping so if we change that to function scoping we'd have to update a ton of tests so that's not really an option at this time.

2023-02-23 18:31 UTC, tmsteere commented
The test failure occurs before the database write, so deleting the nodes isn't going to help. It occurs when trying to parse the task data for the second time. I think the solution we have now is probably the best option given the current configuration as the use case for running a single test on its own is limited.

2023-02-24 02:10 UTC, ryan-lane commented
Are there task definitions that are defined but not used because they're AWS defined tasks or something?

2023-02-24 17:03 UTC, tmsteere commented
They are previous versions that are no longer being used. When you push a new deployment, with a changed docker tag, for example, it creates a new task definition and changes that to the current one. The previous ones are not removed by default so you can end up with hundreds or more unused definitions.

2023-02-25 01:18 UTC, ryan-lane commented
Ah, gotcha. That makes sense! Seems to good to me.

On Sat, Feb 25, 2023, 2:03 AM tmsteere ***@***.***> wrote:

> They are previous versions that are no longer being used. When you push a
> new deployment, with a changed docker tag, for example, it creates a new
> task definition and changes that to the current one. The previous ones are
> not removed by default so you can end up with hundreds or more unused
> definitions.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/lyft/cartography/pull/1127#issuecomment-1444035267>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AALXSMV4BNNOBPDWDWMVLO3WZDSVVANCNFSM6AAAAAAVEWRE4I>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-02-25 01:40 UTC, achantavy requested changes
Leaving some code comments, let me know if you have questions. I'll let @ryan-lane comment on the overall approach.

2023-02-25 01:40 UTC, achantavy commented on cartography/intel/aws/ecs.py
> +        MERGE (task)-[r:HAS_TASK_DEFINITION]->(d)
I think this doc was missing to begin with, but while you're in here can you add a doc entry for `HAS_TASK_DEFINITION` in this schema doc? https://github.com/lyft/cartography/blob/master/docs/root/modules/aws/schema.md#relationships-83

2023-02-27 17:47 UTC, tmsteere commented on cartography/intel/aws/ecs.py
> +            taskDefinition=task.get('taskDefinitionArn'),
Agreed, going with the second approach. This should always be present since the task needs a task definition assigned.

2023-02-27 18:39 UTC, merged