Add support for GitHub teams and team-repos
lyft/cartography pull request #1167
Opened 2023-05-05 02:08 UTC by achantavy

Testing performed

- Integration tests
- Manually ran CLI

2023-05-05 15:02 UTC, resilience-jychp reviewed
Needed feature, thx for the job.
Some non blocking comments.

May be it can be confusing to have a module with both old way & new model queries ...

2023-05-08 21:21 UTC, ramonpetgrave64 requested changes

2023-05-08 21:21 UTC, ramonpetgrave64 commented on cartography/models/github/teams.py
> +    id: PropertyRef = PropertyRef('url')
nonblocker: I feel like id should maybe be `{org}/{name}`, but i see that url was also used for the id of Repos

2023-05-08 21:21 UTC, ramonpetgrave64 commented on tests/integration/cartography/intel/github/test_teams.py
> +    _ensure_local_neo4j_has_test_data(neo4j_session)
Non blocker: add one more test org to make sure teams aren't accidentally added to that other org.

2023-05-08 21:21 UTC, ramonpetgrave64 commented on cartography/intel/github/__init__.py
> +                config.update_tag,
I think we can take away this parameter instead, since the update tag is within common_job_parameters.

2023-05-12 18:07 UTC, ramonpetgrave64 approved these changes

2023-05-12 18:07 UTC, merged