Added support for AWS API Gateway
lyft/cartography pull request #539
Opened 2021-03-01 06:43 UTC by kedarghule

This is an initial version of pulling API Gateway REST APIs, Resources, Stages and the Client Certificate details and populating graph db.

2021-03-02 05:04 UTC, achantavy requested changes
Thanks for submitting this! Left a few minor minor comments.

2021-03-02 05:04 UTC, achantavy commented on cartography/intel/aws/apigateway.py
> +    ON CREATE SET c.firstseen = timestamp(), c.createddate = certificate.createdDate
Same thing about arns

2021-03-02 06:16 UTC, kedarghule commented on cartography/intel/aws/apigateway.py
> +@timeit
@achantavy  I removed the transform_apigateway_rest_apis() function altogether and added it's body within the load_apigateway_rest_apis() function.

2021-03-02 06:17 UTC, kedarghule commented on cartography/intel/aws/apigateway.py
> +@aws_handle_regions
@achantavy Removed it :)

2021-03-02 06:29 UTC, kedarghule commented on cartography/intel/aws/apigateway.py
> +    ON CREATE SET rest_api.firstseen = timestamp(),
@achantavy `id` field is an identifier for the REST API. Rest apis don't have arns so we don't need to capture them.

2021-03-02 06:29 UTC, kedarghule commented on cartography/intel/aws/apigateway.py
> +    MERGE (s:APIGatewayStage{id: stage.stageName})
@achantavy For stages, I created a new field 'arn' since stage name may be same for multiple rest apis.

2021-03-02 06:30 UTC, kedarghule commented on cartography/intel/aws/apigateway.py
> +    ON CREATE SET c.firstseen = timestamp(), c.createddate = certificate.createdDate
@achantavy Client certificates don't have an arn. Just an identifier.

2021-03-02 06:31 UTC, kedarghule commented
@achantavy I've made all the changes as per your review. Please let me know if there are any more changes! :)

2021-03-03 08:56 UTC, achantavy submitted a review, later dismissed
Thanks for your contribution!

2021-03-04 19:50 UTC, achantavy approved these changes
🍻

2021-03-04 19:50 UTC, merged