Add DigitalOcean Intel module
lyft/cartography pull request #550
Opened 2021-03-04 14:03 UTC by lgomezma

The intention of this PR is to add initial support for Intel from DigitalOcean. For that I'm creating a new Intel module making use of the `python-digitalocean` library. This Intel module supports for now only a limited subset of resources in DigitalOcean, which are Account, Projects and Droplets. The initial intention was to only add Droplets on the first iteration, but I found it better to respect DO object hierarchy and start from the top as Account has Projects and a Project has Droplets.

2021-03-04 19:47 UTC, achantavy requested changes
Quick first pass. Thanks for the PR, this is exciting!

2021-03-04 19:47 UTC, achantavy commented on cartography/data/jobs/cleanup/digitalocean_account_cleanup.json
> +      "query": "MATCH (n:Account{id: {DO_ACCOUNT_ID}}) WHERE n.lastupdated <> {UPDATE_TAG} WITH n LIMIT {LIMIT_SIZE} DETACH DELETE (n) return COUNT(*) as TotalCompleted",
Should this be `match(n:DOAccount)`?

2021-03-05 07:26 UTC, lgomezma commented on cartography/data/jobs/cleanup/digitalocean_account_cleanup.json
> +      "query": "MATCH (n:Account{id: {DO_ACCOUNT_ID}}) WHERE n.lastupdated <> {UPDATE_TAG} WITH n LIMIT {LIMIT_SIZE} DETACH DELETE (n) return COUNT(*) as TotalCompleted",
Indeed, good catch!

2021-03-05 16:38 UTC, achantavy approved these changes

2021-03-05 16:39 UTC, merged