Sync AWS Secret Manager data from all regions
lyft/cartography pull request #660
Opened 2021-07-29 08:39 UTC by ryan-lane

This change syncs secret manager data for all regions, rather than just the region that cartography is being run from.

2021-07-29 09:12 UTC, ninjaSec7 submitted a review, later dismissed

2021-07-29 14:50 UTC, kedarghule requested changes
All looks good. One small change and then we can merge. 

PS:  Since a new intel module is being added, add the name here too - https://github.com/lyft/cartography/blob/master/README.md in the Supported Platforms section. I forgot about this last time. (I know I mentioned this in the SQS PR as well, sorry)

2021-07-29 14:50 UTC, kedarghule commented on cartography/intel/aws/secretsmanager.py
> +    client = boto3_session.client('secretsmanager', region_name=region)
Add `@aws_handle_regions` before this function.

2021-07-30 07:08 UTC, kedarghule approved these changes
Looks good! Thank you for the contribution @ryan-lane :D

2021-07-30 07:09 UTC, merged