Add backoff to avoid AWS too many requests exception
lyft/cartography pull request #880
Opened 2022-07-11 14:16 UTC by rlukin

Add backoff to avoid AWS too many requests exception
https://github.com/lyft/cartography/issues/297
https://github.com/lyft/cartography/issues/243
https://github.com/lyft/cartography/issues/65
https://github.com/lyft/cartography/issues/25

2022-07-16 13:38 UTC, rlukin commented
@achantavy signed

2022-07-18 18:04 UTC, achantavy requested changes
Added quick comment about requirements pinning.

The CI is also being picky and complaining about formatting. If you run `make test_lint` locally before pushing your branch, it'll fix it and avoid being rejcted

2022-08-04 05:58 UTC, achantavy approved these changes

2022-08-04 06:03 UTC, achantavy approved these changes

2022-08-04 06:05 UTC, achantavy commented
Hey @rlukin - can you run `make test_lint` on your local machine and push back the results? I tried making a few quick edits with the web editor but I keep missing things here and there.

2022-08-08 21:06 UTC, ramonpetgrave64 approved these changes

2022-08-08 21:06 UTC, merged